# Generated by Django 5.1.1 on 2024-09-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posisi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_posisi', models.CharField(max_length=225)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Posisi',
                'verbose_name_plural': 'Posisi',
            },
        ),
        migrations.CreateModel(
            name='sto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_sto', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'STO',
                'verbose_name_plural': 'STO',
            },
        ),
    ]
