# Generated by Django 5.1.1 on 2024-10-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenisnota',
            name='jenis_nota',
            field=models.CharField(choices=[('BBM', 'BBM'), ('NonBBM', 'Non-BBM')], default='default_value', max_length=255),
        ),
    ]
