# Generated by Django 5.1.1 on 2024-10-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksibbm',
            name='foto_nota',
            field=models.ImageField(upload_to='bbm/notas/'),
        ),
        migrations.AlterField(
            model_name='transaksibbm',
            name='foto_odo',
            field=models.ImageField(upload_to='bbm/odos/'),
        ),
        migrations.AlterField(
            model_name='transaksinonbbm',
            name='foto_evidence',
            field=models.ImageField(upload_to='nonbbm/evidences/'),
        ),
        migrations.AlterField(
            model_name='transaksinonbbm',
            name='foto_nota',
            field=models.ImageField(upload_to='nonbbmnotas/'),
        ),
    ]
