# Generated by Django 4.2.16 on 2024-10-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0002_jenisnota_naker_project_unit_transaksinonbbm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kendaraan',
            old_name='jenis_kbm',
            new_name='jenis_KBM',
        ),
        migrations.RenameField(
            model_name='kendaraan',
            old_name='merk_type_kbm',
            new_name='merk_type_KBM',
        ),
        migrations.RenameField(
            model_name='transaksibbm',
            old_name='jenis_kbm',
            new_name='jenis_KBM',
        ),
        migrations.RenameField(
            model_name='transaksibbm',
            old_name='id_sto',
            new_name='sto',
        ),
        migrations.RemoveField(
            model_name='transaksibbm',
            name='tgl_input',
        ),
        migrations.RemoveField(
            model_name='transaksinonbbm',
            name='tgl_input',
        ),
        migrations.AlterField(
            model_name='transaksibbm',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('processed', 'Processed'), ('verified', 'Verified'), ('paid', 'Paid')], default='Proccessed', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaksinonbbm',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('processed', 'Processed'), ('verified', 'Verified'), ('paid', 'Paid')], default='Proccessed', max_length=10),
        ),
    ]
