# Generated by Django 5.1.1 on 2024-10-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0002_jenisnota_jenis_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='posisi',
            name='jenis_posisi',
            field=models.CharField(choices=[('Manager', 'Manager'), ('AssMAN', 'AssMAN'), ('Supervisor', 'Supervisor'), ('Team Leader', 'Team Leader'), ('Staff', 'Staff'), ('Helpdesk', 'Helpdesk'), ('Teknisi', 'Teknisi')], default='Pilih Posisi', max_length=225),
        ),
        migrations.AlterField(
            model_name='jenisnota',
            name='jenis_nota',
            field=models.CharField(choices=[('BBM', 'BBM'), ('Non-BBM', 'Non-BBM')], default='default_value', max_length=255),
        ),
    ]
