# Generated by Django 5.1.1 on 2024-10-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0003_rename_jenis_kbm_kendaraan_jenis_kbm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kendaraan',
            old_name='foto_tmpak_depan',
            new_name='foto_tampak_depan',
        ),
        migrations.RenameField(
            model_name='transaksibbm',
            old_name='sto',
            new_name='id_sto',
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='merk_type_KBM',
            field=models.CharField(choices=[('Honda Beat', 'Honda Beat'), ('Mitsubishi Expander', 'Mitsubishi Expander')], max_length=100),
        ),
    ]
