# Generated by Django 5.1.1 on 2024-10-03 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0003_posisi_jenis_posisi_alter_jenisnota_jenis_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='natura',
            old_name='id_posisi',
            new_name='posisi',
        ),
        migrations.AddField(
            model_name='natura',
            name='nama',
            field=models.CharField(default='Isi nama', max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='notareport.naker'),
        ),
        migrations.AlterField(
            model_name='naker',
            name='role',
            field=models.ForeignKey(default='default_value', on_delete=django.db.models.deletion.CASCADE, to='notareport.role', to_field='nama_role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='nama_role',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
