# Generated by Django 5.1.1 on 2024-10-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0004_rename_id_posisi_natura_posisi_natura_nama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natura',
            name='posisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notareport.posisi', to_field='nama_posisi'),
        ),
        migrations.AlterField(
            model_name='posisi',
            name='nama_posisi',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
