# Generated by Django 5.1.1 on 2024-10-03 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0004_rename_id_posisi_natura_posisi_natura_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='notareport.naker'),
        ),
    ]
