# Generated by Django 5.1.1 on 2024-10-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0004_rename_foto_tmpak_depan_kendaraan_foto_tampak_depan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kendaraan',
            old_name='NIK_pengguna_KBM',
            new_name='nik_pengguna_kbm',
        ),
    ]
