# Generated by Django 4.2.16 on 2024-10-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0005_alter_myuser_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natura',
            name='harga_bensin',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='natura',
            name='km_liter',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='natura',
            name='km_referensi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='natura',
            name='nama',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
