# Generated by Django 5.1.1 on 2024-10-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0005_rename_nik_pengguna_kbm_kendaraan_nik_pengguna_kbm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kendaraan',
            name='nik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kendaraan_nik', to='notareport.naker'),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='nik_pengguna_kbm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kendaraan_pengguna', to='notareport.naker'),
        ),
    ]
