# Generated by Django 5.1.1 on 2024-10-03 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0005_alter_natura_posisi_alter_posisi_nama_posisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naker',
            name='posisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notareport.posisi', to_field='nama_posisi'),
        ),
    ]
