# Generated by Django 5.1.1 on 2024-10-03 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0006_alter_naker_posisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naker',
            name='posisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notareport.posisi'),
        ),
    ]
