# Generated by Django 5.1.1 on 2024-10-02 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0006_alter_kendaraan_nik_alter_kendaraan_nik_pengguna_kbm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('nik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notareport.naker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
