# Generated by Django 5.1.1 on 2024-10-02 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notareport', '0008_role_naker_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='notareport.naker'),
        ),
    ]
